# Replace __PASTE_SAME_PASSWORD__ below in BOTH places before deploying.
services:
  - type: web
    name: mattermost
    env: image
    plan: starter
    autoDeploy: true
    image:
      url: mattermost/mattermost-team-edition:10.11.1
    healthCheckPath: /
    envVars:
      - key: MM_SQLSETTINGS_DRIVERNAME
        value: postgres
      - key: MM_SQLSETTINGS_DATASOURCE
        value: "postgres://mmuser:__PASTE_SAME_PASSWORD__@postgres:5432/mattermost?sslmode=disable&connect_timeout=10"
      - key: MM_SERVICESETTINGS_LISTENADDRESS
        value: ":8065"
      - key: MM_FILESETTINGS_DIRECTORY
        value: "/mattermost/data"
      - key: MM_PLUGINSETTINGS_ENABLEUPLOADS
        value: "true"
      - key: MM_SERVICESETTINGS_SITEURL
        value: ""   # set to your HTTPS domain later (optional)
    disk:
      name: mm-data
      mountPath: /mattermost/data
      sizeGB: 10

  - type: pserv
    name: postgres
    env: image
    plan: starter
    autoDeploy: true
    image:
      url: postgres:16-alpine
    envVars:
      - key: POSTGRES_DB
        value: "mattermost"
      - key: POSTGRES_USER
        value: "mmuser"
      - key: POSTGRES_PASSWORD
        value: "__PASTE_SAME_PASSWORD__"
    disk:
      name: pg-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
