# Render blueprint: coturn as a private service (TCP 3478 only — Render doesn't expose UDP)
services:
  - type: pserv
    name: coturn
    env: image
    plan: starter
    autoDeploy: false
    image:
      url: coturn/coturn:latest
      # Override container CMD (use TCP 3478)
      command:
        - sh
        - -lc
        - >
          turnserver -n --log-file=stdout
          --realm=${TURN_REALM}
          --user=${TURN_USER}:${TURN_PASS}
          --fingerprint
          --listening-ip=0.0.0.0
          --listening-port=3478
          --min-port=49152 --max-port=49999
          --no-tls --no-dtls
          ${EXTERNAL_IP:+--external-ip=${EXTERNAL_IP}}
    # Render pserv ports: TCP only
    ports:
      - port: 3478
    envVars:
      - key: TURN_REALM
        value: "mattermost-9g8i.onrender.com"
      - key: TURN_USER
        value: "turnuser"
      - key: TURN_PASS
        value: "turnpass"
      - key: EXTERNAL_IP
        value: ""
